[build]
  functions = "js"  # Directory for Netlify functions
  publish = "."     # Directory to publish

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
